name: Deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        with:
          version: 10

      - uses: actions/setup-node@v7
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: apps/web/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: apps/web

      - name: Build application
        run: pnpm run build
        working-directory: apps/web

      - name: Audit dependencies
        run: pnpm audit --audit-level critical
        working-directory: apps/web

  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        with:
          version: 10

      - uses: actions/setup-node@v7
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: apps/web/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: apps/web

      - name: Build application
        run: pnpm run build
        working-directory: apps/web

      - name: Audit dependencies
        run: pnpm audit --audit-level critical
        working-directory: apps/web

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Terraform 
        working-directory: infra

        run: |
          terraform init
          terraform apply -auto-approve
      - name: Upload website to S3
        run: |
          aws s3 sync apps/web/dist s3://nextfoundry.co.uk --delete --region eu-west-2

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E2YL68ORAJN6JV \
            --paths "/*"
